# Generated by Django 3.1.6 on 2021-02-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claims',
            options={'verbose_name_plural': 'Claims'},
        ),
    ]
