# Generated by Django 3.1.6 on 2021-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0002_auto_20210209_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='anybody_injured',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
